name: guard-find-server
services:
  guard-find-server-mysql:
    image: mysql:8.0.42
    container_name: guard-find-server-mysql
    restart: always
    ports:
      - '13306:3306'
    volumes:
      - /docker/guard-find-server/mysql/conf/:/etc/mysql/conf.d/
      - /docker/guard-find-server/mysql/data/:/var/lib/mysql/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 你的root用户密码
      MYSQL_DATABASE: guard_find_server
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1
  guard-find-server-redis:
    image: redis:7.2.8
    container_name: guard-find-server-redis
    restart: always
    ports:
      - '16379:6379'
    volumes:
      - /docker/guard-find-server/redis/conf/redis.conf:/usr/local/redis/config/redis.conf
      - /docker/guard-find-server/redis/data/:/data/
      - /docker/guard-find-server/redis/logs/:/logs/
    environment:
      TZ: Asia/Shanghai
    command: 'redis-server /usr/local/redis/config/redis.conf --appendonly yes'
  guard-find-server-api:
    build: ./guard-find-server-api
    image: guard-find-server-api:4.2.0-SNAPSHOT
    container_name: guard-find-server-api
    restart: always
    ports:
      - '18000:18000'
      - '17889:17889'
    volumes:
      - /docker/guard-find-server/api/config/:/app/config/
      - /docker/guard-find-server/api/data/file/:/app/data/file/
      - /docker/guard-find-server/api/logs/:/app/logs/
      - /docker/guard-find-server/api/lib/:/app/lib/
    environment:
      TZ: Asia/Shanghai
      PROFILES_ACTIVE: prod
      DB_HOST: guard-find-server-mysql
      DB_PORT: 3306
      DB_USER: 你的数据库用户名
      DB_PWD: 你的数据库密码
      DB_NAME: guard_find_server
      REDIS_HOST: guard-find-server-redis
      REDIS_PORT: 6379
      REDIS_PWD: 你的 Redis 密码
      REDIS_DB: 0
      SCHEDULE_HOST: guard-find-server-schedule
      SCHEDULE_PORT: 1788
      SCHEDULE_TOKEN: 任务调度服务端 Token
    depends_on:
      - guard-find-server-mysql
      - guard-find-server-redis
  guard-find-server-schedule:
    build: ./guard-find-server-schedule
    image: guard-find-server-schedule:1.8.0
    container_name: guard-find-server-schedule
    restart: always
    ports:
      - '18001:18001'
      - '17888:17888'
    volumes:
      - /docker/guard-find-server/schedule/logs/:/app/logs/
    environment:
      TZ: Asia/Shanghai
      DB_HOST: guard-find-server-mysql
      DB_PORT: 3306
      DB_USER: 你的数据库用户名
      DB_PWD: 你的数据库密码
      DB_NAME: guard_find_server_job
    depends_on:
      - guard-find-server-mysql
